/* Built-in sound-effect stamps — ready-made SFX artwork that ships with the
   app and is placed the same way as any imported image. `s` is the file under
   /stamps, `l` the label shown in the picker and matched when searching. */
export interface SfxStamp { s: string; l: string }

export const SFX_STAMPS: SfxStamp[] = [
  { s: "exclexclexcl", l: "!!!" },
  { s: "sigh", l: "Sigh..." },
  { s: "a-haexcl", l: "a-ha!" },
  { s: "aaaccchexcl", l: "aaaccch!" },
  { s: "aaahhh", l: "aaahhh" },
  { s: "ah-choooexcl", l: "ah-chooo!" },
  { s: "ahh", l: "ahh" },
  { s: "ai-eeeeexcl", l: "ai-eeee!" },
  { s: "aieeeeeee", l: "aieeeeeee" },
  { s: "aignh", l: "aignh" },
  { s: "arrohexcl", l: "arroh!" },
  { s: "bam", l: "bam" },
  { s: "bangexcl-blue", l: "bang! blue" },
  { s: "bangexcl", l: "bang!" },
  { s: "bash", l: "bash" },
  { s: "beep-beep", l: "beep-beep" },
  { s: "belch", l: "belch" },
  { s: "biff", l: "biff" },
  { s: "blam-blam", l: "blam blam" },
  { s: "blip", l: "blip" },
  { s: "bloonk", l: "bloonk" },
  { s: "bloop", l: "bloop" },
  { s: "blurp", l: "blurp" },
  { s: "boff", l: "boff" },
  { s: "bongg", l: "bongg" },
  { s: "bonk", l: "bonk" },
  { s: "boom", l: "boom" },
  { s: "boooo", l: "boooo" },
  { s: "braka-thoom", l: "braka-thoom" },
  { s: "brinng", l: "brinng" },
  { s: "broken-heart", l: "broken heart" },
  { s: "brrrrrr", l: "brrrrrr" },
  { s: "budda-budda", l: "budda budda" },
  { s: "bweee", l: "bweee" },
  { s: "bzzztt", l: "bzzztt" },
  { s: "chak", l: "chak" },
  { s: "chik-chak", l: "chik chak" },
  { s: "chomp", l: "chomp" },
  { s: "choom", l: "choom" },
  { s: "clank", l: "clank" },
  { s: "clash", l: "clash" },
  { s: "clunk", l: "clunk" },
  { s: "craaack", l: "craaack" },
  { s: "crack", l: "crack" },
  { s: "crack1", l: "crack1" },
  { s: "crash", l: "crash" },
  { s: "crunch", l: "crunch" },
  { s: "cunssstt", l: "cunssstt" },
  { s: "ding-dong", l: "ding dong" },
  { s: "eee-yowexcl", l: "eee-yow!" },
  { s: "eeeeeeexcl", l: "eeeeee!" },
  { s: "fizzzz", l: "fizzzz" },
  { s: "floosh", l: "floosh" },
  { s: "flooshsh", l: "flooshsh" },
  { s: "flrbbbb", l: "flrbbbb" },
  { s: "foom", l: "foom" },
  { s: "fump", l: "fump" },
  { s: "fwachoom", l: "fwachoom" },
  { s: "fwap", l: "fwap" },
  { s: "fwip", l: "fwip" },
  { s: "fwoom", l: "fwoom" },
  { s: "fwoosh", l: "fwoosh" },
  { s: "fwump", l: "fwump" },
  { s: "gaaahhexcl", l: "gaaahh!" },
  { s: "gaahexcl", l: "gaah!" },
  { s: "gaspexcl", l: "gasp!" },
  { s: "glurp", l: "glurp" },
  { s: "goodness-sassy", l: "goodness sassy" },
  { s: "groan", l: "groan" },
  { s: "grrroarr", l: "grrroarr" },
  { s: "grrrrrr", l: "grrrrrr" },
  { s: "gulp", l: "gulp" },
  { s: "gwaash", l: "gwaash" },
  { s: "haha", l: "haha" },
  { s: "hahahaha-blue", l: "hahahaha blue" },
  { s: "hahahahaexcl", l: "hahahaha!" },
  { s: "hehehe", l: "hehehe" },
  { s: "helpexcl", l: "help!" },
  { s: "hi-yaexcl", l: "hi-ya!" },
  { s: "hnnh", l: "hnnh" },
  { s: "honkk", l: "honkk" },
  { s: "huff-sexy", l: "huff sexy" },
  { s: "idea", l: "idea" },
  { s: "ka-boom", l: "ka-boom" },
  { s: "ka-powexcl", l: "ka-pow!" },
  { s: "kachow", l: "kachow" },
  { s: "kchoom", l: "kchoom" },
  { s: "ker-plop", l: "ker-plop" },
  { s: "ker-sploosh", l: "ker-sploosh" },
  { s: "kiss", l: "kiss" },
  { s: "kkraka-bam", l: "kkraka-bam" },
  { s: "klang", l: "klang" },
  { s: "klik-klak", l: "klik-klak" },
  { s: "klik", l: "klik" },
  { s: "klonkk", l: "klonkk" },
  { s: "knock-knock", l: "knock knock" },
  { s: "kraaak", l: "kraaak" },
  { s: "krak", l: "krak" },
  { s: "kreeek", l: "kreeek" },
  { s: "kroom", l: "kroom" },
  { s: "krunch", l: "krunch" },
  { s: "lick", l: "lick" },
  { s: "love-hearts", l: "love hearts" },
  { s: "moan-sexy", l: "moan...sexy" },
  { s: "munch-munch", l: "munch munch" },
  { s: "music-3", l: "music 3" },
  { s: "music-green", l: "music green" },
  { s: "noexcl", l: "no!" },
  { s: "noooo", l: "noooo" },
  { s: "noooooo", l: "noooooo" },
  { s: "oh-myexcl", l: "oh my!" },
  { s: "oh-noexcl", l: "oh no!" },
  { s: "ohexcl", l: "oh!" },
  { s: "ooof", l: "ooof" },
  { s: "oooffexcl", l: "oooff!" },
  { s: "ooohhh", l: "ooohhh" },
  { s: "ooooooohhhh", l: "ooooooohhhh" },
  { s: "ooopsexcl", l: "ooops!" },
  { s: "ouchexclexcl", l: "ouch!!" },
  { s: "owexcl-red", l: "ow! red" },
  { s: "owexcl", l: "ow!" },
  { s: "owwwexcl", l: "owww!" },
  { s: "pam", l: "pam" },
  { s: "pant", l: "pant" },
  { s: "plop", l: "plop" },
  { s: "poom", l: "poom" },
  { s: "pop", l: "pop" },
  { s: "powexcl", l: "pow!" },
  { s: "question-3", l: "question 3" },
  { s: "qunckkk", l: "qunckkk" },
  { s: "qwumppp", l: "qwumppp" },
  { s: "rakkk", l: "rakkk" },
  { s: "rarrgh", l: "rarrgh" },
  { s: "ratatatata", l: "ratatatata" },
  { s: "rip", l: "rip" },
  { s: "rrragh", l: "rrragh" },
  { s: "rrrfff", l: "rrrfff" },
  { s: "rrring", l: "rrring" },
  { s: "rummmble", l: "rummmble" },
  { s: "sfffzzz", l: "sfffzzz" },
  { s: "sffwoosh", l: "sffwoosh" },
  { s: "shexcl", l: "sh!" },
  { s: "shhhh", l: "shhhh" },
  { s: "shlak", l: "shlak" },
  { s: "shriek", l: "shriek" },
  { s: "shrrackk", l: "shrrackk" },
  { s: "sizzle", l: "sizzle" },
  { s: "skrangg", l: "skrangg" },
  { s: "skrashexcl", l: "skrash!" },
  { s: "skrashh", l: "skrashh" },
  { s: "skreee", l: "skreee" },
  { s: "skrrrk", l: "skrrrk" },
  { s: "slamexcl", l: "slam!" },
  { s: "slap", l: "slap" },
  { s: "slice", l: "slice" },
  { s: "slish", l: "slish" },
  { s: "slkkk", l: "slkkk" },
  { s: "slosh", l: "slosh" },
  { s: "smack", l: "smack" },
  { s: "smakk", l: "smakk" },
  { s: "smooch", l: "smooch" },
  { s: "sniff", l: "sniff" },
  { s: "snikt", l: "snikt" },
  { s: "snort", l: "snort" },
  { s: "sob", l: "sob" },
  { s: "sock", l: "sock" },
  { s: "spack", l: "spack" },
  { s: "spak", l: "spak" },
  { s: "spash", l: "spash" },
  { s: "spdoing", l: "spdoing" },
  { s: "splat", l: "splat" },
  { s: "spluchtt", l: "spluchtt" },
  { s: "splunk", l: "splunk" },
  { s: "spok", l: "spok" },
  { s: "spoosh", l: "spoosh" },
  { s: "svvvzzmmm", l: "svvvzzmmm" },
  { s: "swaap", l: "swaap" },
  { s: "swoosh", l: "swoosh" },
  { s: "tchoom", l: "tchoom" },
  { s: "thack", l: "thack" },
  { s: "thak", l: "thak" },
  { s: "thhnnk", l: "thhnnk" },
  { s: "thik", l: "thik" },
  { s: "thooch", l: "thooch" },
  { s: "thoom", l: "thoom" },
  { s: "thrakoom", l: "thrakoom" },
  { s: "throb", l: "throb" },
  { s: "thud", l: "thud" },
  { s: "thump", l: "thump" },
  { s: "thunk", l: "thunk" },
  { s: "thwack", l: "thwack" },
  { s: "thwapp", l: "thwapp" },
  { s: "thwip", l: "thwip" },
  { s: "thwp", l: "thwp" },
  { s: "uffexcl", l: "uff!" },
  { s: "ughexcl", l: "ugh!" },
  { s: "ugh", l: "ugh" },
  { s: "uhh", l: "uhh" },
  { s: "unngh", l: "unngh" },
  { s: "urkkkexcl", l: "urkkk!" },
  { s: "vooor", l: "vooor" },
  { s: "voosh", l: "voosh" },
  { s: "vvroom", l: "vvroom" },
  { s: "vwwrreee", l: "vwwrreee" },
  { s: "vzap", l: "vzap" },
  { s: "waagghh", l: "waagghh" },
  { s: "wail", l: "wail" },
  { s: "wap", l: "wap" },
  { s: "weeoooweeooo", l: "weeoooweeooo" },
  { s: "wha-red", l: "wha red" },
  { s: "wha", l: "wha" },
  { s: "whack", l: "whack" },
  { s: "whamm", l: "whamm" },
  { s: "whap", l: "whap" },
  { s: "what-alert", l: "what alert" },
  { s: "what", l: "what" },
  { s: "whimper", l: "whimper" },
  { s: "whip", l: "whip" },
  { s: "whish", l: "whish" },
  { s: "whoaexcl", l: "whoa!" },
  { s: "whoa", l: "whoa" },
  { s: "whoosh", l: "whoosh" },
  { s: "whuff", l: "whuff" },
  { s: "whumf", l: "whumf" },
  { s: "wink", l: "wink" },
  { s: "wrrrp", l: "wrrrp" },
  { s: "wunk", l: "wunk" },
  { s: "wzzzt", l: "wzzzt" },
  { s: "yee-haaaexcl", l: "yee-haaa!" },
  { s: "yeowexcl", l: "yeow!" },
  { s: "yes", l: "yes" },
  { s: "zam", l: "zam" },
  { s: "zap", l: "zap" },
  { s: "zing", l: "zing" },
  { s: "zip", l: "zip" },
  { s: "zlonk", l: "zlonk" },
  { s: "zlott", l: "zlott" },
  { s: "zok", l: "zok" },
  { s: "zombie-fuck", l: "zombie fuck" },
  { s: "zoom", l: "zoom" },
  { s: "zweee", l: "zweee" },
  { s: "zzakk", l: "zzakk" },
  { s: "zzchzzt", l: "zzchzzt" },
  { s: "zzmmmshrummm", l: "zzmmmshrummm" },
  { s: "zzzwap", l: "zzzwap" },
  { s: "zzzz", l: "zzzz" },
];
